### PR TITLE
Tlposts

### PR DESCRIPTION
**Pull request by Tlane77**
# Description
Given a user is in the app
When they select the New Post menu option
Then they should be directed to a page with a form for creating a new post, edit a post and delete a post and be directed back to appropriate page
Fixes # (edit and delete not working.#3,#4,#6 #8 )
## Type of change 
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue upon build so routes are correct)
- [x] New feature (non-breaking change which adds functionality (added edit and delete with SYSDATE)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected, URL length, and Current or Prior Date Addressed)
# Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests.
-Login via admin
-Click on Posts
-Add New Post, Edit the New Post return to details, Delete New Post return to Index

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ xx] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Tlane77** [comment]
DELETE #7 Has been Added to this pull -request as it's fully functional.

**Review by TriggSumms — APPROVED** [review]

**Review by chadjones839 — APPROVED** [review]
Full CRUD works on posts, except on posts with comments. Known bug that will be fixed in next post update.

**Review by chadjones839 — CHANGES_REQUESTED** [review]
Need to pull master with comment controller options

**Comment by Tlane77** [comment]
Reuploading with new Master

**Comment by Tlane77** [comment]
Branch Not Uploading Correctly.

**Pull request closed without merging**
